name: Deploy WordPress App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - app/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        working-directory: infra/envs/dev
        run: terraform init

      - name: Download outputs
        uses: actions/download-artifact@v4
        with:
          name: tf-outputs
          path: .

      - name: Parse outputs
        run: |
          BUCKET=$(jq -r .bucket_name.value tf_outputs.json)
          echo "bucket_name=$BUCKET" >> $GITHUB_ENV
  

      - name: Get Terraform outputs
        working-directory: infra/envs/dev
        run: terraform output -json > tf_outputs.json

      - name: Parse Terraform outputs
        id: tf
        run: |
          echo "bucket_name=$(jq -r .bucket_name.value tf_outputs.json)" >> $GITHUB_ENV
          echo "ec2_host=$(jq -r .ec2_instance_public_ip.value tf_outputs.json)" >> $GITHUB_ENV
          echo "db_endpoint=$(jq -r .db_endpoint.value tf_outputs.json)" >> $GITHUB_ENV
          echo "alb_dns_name=$(jq -r .alb_dns_name.value tf_outputs.json)" >> $GITHUB_ENV

      - name: Zip WordPress artifact
        run: zip -r wordpress.zip app/

      - name: Upload artifact to S3
        run: aws s3 cp wordpress.zip s3://$bucket_name/wordpress.zip --region $AWS_DEFAULT_REGION

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.ec2_host }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws s3 cp s3://$bucket_name/wordpress.zip /tmp/wordpress.zip --region $AWS_DEFAULT_REGION
            unzip -o /tmp/wordpress.zip -d /var/www/html
            systemctl restart httpd

      - name: Post-deploy info
        run: |
          echo "WordPress should now be accessible at: http://${alb_dns_name}"
